import {
  pgTable,
  text,
  varchar,
  pgEnum,
  timestamp,
  boolean,
  uuid,
  jsonb,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// --- Enums ---
export const roleEnum = pgEnum("role", ["admin", "editor", "writer", "user"]);

// --- Identity Layer ---
export const users = pgTable("users", {
  id: uuid("id").primaryKey(), // Managed by Supabase Auth
  email: varchar("email", { length: 255 }).notNull().unique(),
  role: roleEnum("role").default("user").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const profiles = pgTable("profiles", {
  id: uuid("id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  fullName: varchar("full_name", { length: 255 }),
  bio: text("bio"),
  avatarUrl: text("avatar_url"),
  socialLinks: jsonb("social_links"), // Keep it flexible for various social media profiles
});

// --- Taxonomy Layer ---
export const categories = pgTable("categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  description: text("description"),
  isActive: boolean("is_active").default(true).notNull(),
});

export const tags = pgTable("tags", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
});

// --- Content Layer ---
export const articles = pgTable("articles", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  // Generated by TipTap Editor in the CMS
  contentHtml: text("content_html").notNull(),
  excerpt: text("excerpt"),
  coverImageUrl: text("cover_image_url"),

  // Publishing Workflow
  isPublished: boolean("is_published").default(false).notNull(),
  publishedAt: timestamp("published_at"),

  // Links to the Profile of the writer
  authorId: uuid("author_id")
    .notNull()
    .references(() => users.id),

  // Links to the Admin who effectively submitted/approved it in the CMS
  createdByAdminId: uuid("created_by_admin_id")
    .notNull()
    .references(() => users.id),

  categoryId: uuid("category_id").references(() => categories.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (t) => {
  return [
    index("articles_published_idx").on(t.isPublished, t.publishedAt),
    index("articles_author_idx").on(t.authorId),
    index("articles_category_idx").on(t.categoryId)
  ]
});

// Junction table for Articles <-> Tags
export const articleTags = pgTable("article_tags", {
  articleId: uuid("article_id")
    .references(() => articles.id, { onDelete: "cascade" })
    .notNull(),
  tagId: uuid("tag_id")
    .references(() => tags.id, { onDelete: "cascade" })
    .notNull(),
}, (t) => {
  return [
    primaryKey({ name: "article_tags_pk", columns: [t.articleId, t.tagId] })
  ]
});

// --- Relationships (For easier nested queries) ---
export const usersRelations = relations(users, ({ one, many }) => ({
  profile: one(profiles, {
    fields: [users.id],
    references: [profiles.id],
  }),
  articles: many(articles, { relationName: "authorArticles" }),
  createdArticles: many(articles, { relationName: "adminArticles" }),
}));

export const articlesRelations = relations(articles, ({ one, many }) => ({
  author: one(users, {
    fields: [articles.authorId],
    references: [users.id],
    relationName: "authorArticles",
  }),
  createdByAdmin: one(users, {
    fields: [articles.createdByAdminId],
    references: [users.id],
    relationName: "adminArticles",
  }),
  category: one(categories, {
    fields: [articles.categoryId],
    references: [categories.id],
  }),
  tags: many(articleTags),
}));

export const articleTagsRelations = relations(articleTags, ({ one }) => ({
  article: one(articles, {
    fields: [articleTags.articleId],
    references: [articles.id],
  }),
  tag: one(tags, {
    fields: [articleTags.tagId],
    references: [tags.id],
  }),
}));
